# this file contains sets and dictionaries of search words
eu_nordic_countries = {"austria",
                       "belgium",
                       "croatia",
                       "cyprus",
                       "czech republic",
                       "denmark",
                       "estonia",
                       "finland",
                       "france",
                       "germany",
                       "greece",
                       "hungary",
                       "iceland",
                       "ireland",
                       "italy",
                       "latvia",
                       "lithuania",
                       "luxembourg",
                       "malta",
                       "netherlands",
                       "norway",
                       "poland",
                       "portugal",
                       "romania",
                       "slovakia",
                       "slovenia",
                       "spain",
                       "sweden"
                       }


sectors_dict = {"energy": [],
                "transport": [],
                "banking": [],
                "fin_markt_infra": [],
                "health": [],
                "drink_water": [],
                "waste_water": [],
                "digital_infra": [],
                "public_admin": [],
                "space": [],
                "food": []
                }