eu_nordic_countries = {"austria",
                       "belgium",
                       "croatia",
                       "cyprus",
                       "czech republic",
                       "denmark",
                       "estonia",
                       "finland",
                       "france",
                       "germany",
                       "greece",
                       "hungary",
                       "iceland",
                       "ireland",
                       "italy",
                       "latvia",
                       "lithuania",
                       "luxembourg",
                       "malta",
                       "netherlands",
                       "norway",
                       "poland",
                       "portugal",
                       "romania",
                       "slovakia",
                       "slovenia",
                       "spain",
                       "sweden"}